import "./globals.css";
import { Inter } from "next/font/google";
import AuthenticationGate from "@/components/authenticationGate";
import { NextAuthProvider } from "@/components/sessionProvider";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <AuthenticationGate>
            <div className="flex flex-col h-screen">
              <Navbar />
              <main className=" flex-1 my-8">{children}</main>
            </div>
          </AuthenticationGate>
        </NextAuthProvider>
      </body>
    </html>
  );
}
