name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        DEBUG_PASSWORD: ${{ secrets.SSH_IP_ADDRESS }}
        DEBUG_SECRET_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      run: |
        echo $DEBUG_PASSWORD
        echo $DEBUG_SECRET_KEY
      
    - name: SSH to private server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_IP_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PUBLIC_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/bui/chat-app/messanger-web
            git checkout main
            git pull
            docker-compose down
            yes | docker image prune -a
            docker-compose up --build -d
